name: Linting

on:
  push:
    paths-ignore:
      - '**/.gitignore'
      - LICENSE
      - README.md

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
