name: lint

on:
  push:
    paths-ignore:
      - '**/.gitignore'
      - LICENSE
      - README.md

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:latest
    steps:
      - name: Install `file`
        run: apk update && apk add file
      - uses: actions/checkout@v3
      - name: Find shell scripts
        id: find-shell-scripts
        run: printf "shell_scripts=%s\n" "$(file -F' ' * | awk '/shell script/ { printf("%s ", $1) }')" >> $GITHUB_OUTPUT
      - name: Run ShellCheck
        run: shellcheck ${{ steps.find-shell-scripts.outputs.shell_scripts }}
